services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: meu_app_development
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: meu_app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
    - "./meu_app:/meu_app"
    ports:
    - "3000:3000"
    depends_on:
    - db